//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.SourceMappings = new HashSet<SourceMapping>();
        }
    
        public System.Guid FiletId { get; set; }
        public string FileDescription { get; set; }
        public string FileLocation { get; set; }
        public string FileContent { get; set; }
        public Nullable<System.DateTime> FileEntryAdded { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<int> FilerUserAdded { get; set; }
        public string FileThumbLocation { get; set; }
    
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
    }
}
