//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDictionary
    {
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public string LocationCounty { get; set; }
        public Nullable<System.Guid> ParishId { get; set; }
    }
}
