//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarriageRelation
    {
        public int MarriageRelationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string MarriageRelationNotes { get; set; }
    
        public virtual Marriage MarriageA { get; set; }
        public virtual Marriage MarriageB { get; set; }
        public virtual RelationType RelationType { get; set; }
    }
}
