//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marriage
    {
        public Marriage()
        {
            this.SourceMappings = new HashSet<SourceMapping>();
            this.MarriageMapWitness = new HashSet<MarriageMapWitness>();
        }
    
        public System.Guid Marriage_Id { get; set; }
        public string MaleCName { get; set; }
        public string MaleSName { get; set; }
        public string MaleLocation { get; set; }
        public string MaleInfo { get; set; }
        public string FemaleCName { get; set; }
        public string FemaleSName { get; set; }
        public string FemaleLocation { get; set; }
        public string FemaleInfo { get; set; }
        public string Date { get; set; }
        public string MarriageLocation { get; set; }
        public Nullable<int> YearIntVal { get; set; }
        public string MarriageCounty { get; set; }
        public string Source { get; set; }
        public string Witness1 { get; set; }
        public string Witness2 { get; set; }
        public string Witness3 { get; set; }
        public string Witness4 { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateLastEdit { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OrigMaleSurname { get; set; }
        public string OrigFemaleSurname { get; set; }
        public string MaleOccupation { get; set; }
        public string FemaleOccupation { get; set; }
        public Nullable<bool> FemaleIsKnownWidow { get; set; }
        public Nullable<bool> MaleIsKnownWidower { get; set; }
        public Nullable<bool> IsBanns { get; set; }
        public Nullable<bool> IsLicence { get; set; }
        public Nullable<System.Guid> MarriageLocationId { get; set; }
        public Nullable<System.Guid> MaleLocationId { get; set; }
        public Nullable<System.Guid> FemaleLocationId { get; set; }
        public Nullable<int> MaleBirthYear { get; set; }
        public Nullable<int> FemaleBirthYear { get; set; }
        public Nullable<System.Guid> UniqueRef { get; set; }
        public Nullable<int> TotalEvents { get; set; }
        public Nullable<int> EventPriority { get; set; }
        public Nullable<System.Guid> MaleId { get; set; }
        public Nullable<System.Guid> FemaleId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsComposite { get; set; }
    
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
        public virtual ICollection<MarriageMapWitness> MarriageMapWitness { get; set; }
    }
}
