//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarriageMapWitness
    {
        public int MarriageMapWitnessIndex { get; set; }
        public string WitnessNote { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Person Persons { get; set; }
        public virtual Marriage Marriages { get; set; }
    }
}
