//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParishTranscriptionDetail
    {
        public int ParishTranscriptionId { get; set; }
        public string ParishDataString { get; set; }
    
        public virtual Parish Parish { get; set; }
    }
}
