//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParishRecord
    {
        public int ParishRecordsId { get; set; }
        public Nullable<int> Year { get; set; }
        public string RecordType { get; set; }
        public Nullable<bool> OriginalRegister { get; set; }
        public Nullable<int> YearEnd { get; set; }
    
        public virtual ParishRecordSource ParishRecordSource { get; set; }
        public virtual Parish Parish { get; set; }
    }
}
