//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParishCounter
    {
        public int RangeId { get; set; }
        public Nullable<int> YearStart { get; set; }
        public Nullable<int> YearEnd { get; set; }
        public Nullable<System.Guid> ParishId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> PX { get; set; }
        public Nullable<decimal> PY { get; set; }
        public string ParishName { get; set; }
    }
}
