//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public Parish()
        {
            this.SourceMappingParishs = new HashSet<SourceMappingParish>();
            this.ParishTranscriptionDetails = new HashSet<ParishTranscriptionDetail>();
            this.ParishRecords = new HashSet<ParishRecord>();
            this.MissingRecords = new HashSet<MissingRecord>();
        }
    
        public System.Guid ParishId { get; set; }
        public string ParishName { get; set; }
        public string ParishRegistersDeposited { get; set; }
        public string ParishNotes { get; set; }
        public string ParentParish { get; set; }
        public int ParishStartYear { get; set; }
        public int ParishEndYear { get; set; }
        public string ParishCounty { get; set; }
        public Nullable<decimal> ParishX { get; set; }
        public Nullable<decimal> ParishY { get; set; }
        public Nullable<decimal> Distance { get; set; }
    
        public virtual ICollection<SourceMappingParish> SourceMappingParishs { get; set; }
        public virtual ICollection<ParishTranscriptionDetail> ParishTranscriptionDetails { get; set; }
        public virtual ICollection<ParishRecord> ParishRecords { get; set; }
        public virtual ICollection<MissingRecord> MissingRecords { get; set; }
    }
}
