//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.RelationA = new HashSet<Relation>();
            this.RelationB = new HashSet<Relation>();
            this.SourceMappings = new HashSet<SourceMapping>();
            this.MarriageMapWitnesses = new HashSet<MarriageMapWitness>();
        }
    
        public System.Guid Person_id { get; set; }
        public int MotherId { get; set; }
        public int FatherId { get; set; }
        public bool IsMale { get; set; }
        public string ChristianName { get; set; }
        public string Surname { get; set; }
        public string BirthLocation { get; set; }
        public string BirthDateStr { get; set; }
        public string BaptismDateStr { get; set; }
        public string DeathDateStr { get; set; }
        public string DeathLocation { get; set; }
        public string FatherChristianName { get; set; }
        public string FatherSurname { get; set; }
        public string MotherChristianName { get; set; }
        public string MotherSurname { get; set; }
        public string Notes { get; set; }
        public string Source { get; set; }
        public int BirthInt { get; set; }
        public int BapInt { get; set; }
        public int DeathInt { get; set; }
        public string DeathCounty { get; set; }
        public string BirthCounty { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateLastEdit { get; set; }
        public int UserId { get; set; }
        public string OrigSurname { get; set; }
        public string OrigFatherSurname { get; set; }
        public string OrigMotherSurname { get; set; }
        public string Occupation { get; set; }
        public string ReferenceLocation { get; set; }
        public string ReferenceDateStr { get; set; }
        public int ReferenceDateInt { get; set; }
        public string SpouseName { get; set; }
        public string SpouseSurname { get; set; }
        public string FatherOccupation { get; set; }
        public System.Guid BirthLocationId { get; set; }
        public System.Guid DeathLocationId { get; set; }
        public System.Guid ReferenceLocationId { get; set; }
        public Nullable<System.Guid> UniqueRef { get; set; }
        public int TotalEvents { get; set; }
        public int EventPriority { get; set; }
        public int EstBirthYearInt { get; set; }
        public int EstDeathYearInt { get; set; }
        public bool IsEstBirth { get; set; }
        public bool IsEstDeath { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Relation> RelationA { get; set; }
        public virtual ICollection<Relation> RelationB { get; set; }
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
        public virtual ICollection<MarriageMapWitness> MarriageMapWitnesses { get; set; }
    }
}
