//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationTypes
    {
        public RelationTypes()
        {
            this.Relations = new HashSet<Relations>();
        }
    
        public int RelationTypeId { get; set; }
        public string RelationName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual ICollection<Relations> Relations { get; set; }
    }
}
