//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceMapping
    {
        public int MappingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Marriage Marriage { get; set; }
        public virtual Source Source { get; set; }
        public virtual SourceType SourceType { get; set; }
        public virtual File File { get; set; }
        public virtual Person Person { get; set; }
    }
}
