//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.SourceMappingParishs = new HashSet<SourceMappingParish>();
            this.SourceMappings = new HashSet<SourceMapping>();
        }
    
        public System.Guid SourceId { get; set; }
        public string SourceRef { get; set; }
        public Nullable<int> SourceDate { get; set; }
        public Nullable<int> SourceDateTo { get; set; }
        public string SourceDateStr { get; set; }
        public string SourceDateStrTo { get; set; }
        public string SourceDescription { get; set; }
        public string OriginalLocation { get; set; }
        public Nullable<bool> IsCopyHeld { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<bool> IsThackrayFound { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int UserId { get; set; }
        public string SourceNotes { get; set; }
        public Nullable<int> SourceFileCount { get; set; }
        public int SourcePersonCount { get; set; }
        public int SourceMarriageCount { get; set; }
    
        public virtual ICollection<SourceMappingParish> SourceMappingParishs { get; set; }
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
    }
}
