//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDBCore.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceType
    {
        public SourceType()
        {
            this.SourceMappings = new HashSet<SourceMapping>();
        }
    
        public int SourceTypeId { get; set; }
        public string SourceTypeDesc { get; set; }
        public string SourceDateAdded { get; set; }
        public Nullable<int> SourceUserAdded { get; set; }
        public int SourceTypeOrder { get; set; }
    
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
    }
}
