namespace TDBCore.Types.domain.import
{
    public enum CSVField 
    {
        IsMale,
        ChristianName, 
        Surname, 
        BirthLocation, 
        BirthDateStr, 
        BaptismDateStr, 
        DeathDateStr, 
        DeathLocation, 
        FatherChristianName, 
        FatherSurname,
        MotherChristianName,
        MotherSurname, 
        Notes, 
        Source, 
        BirthInt,
        BapInt , 
        DeathInt , 
        DeathCounty ,
        BirthCounty , 
        Occupation , 
        ReferenceLocation , 
        ReferenceDateStr , 
        ReferenceDateInt , 
        SpouseName , 
        SpouseSurname , 
        FatherOccupation , 
        AgeYear , 
        AgeMonth , 
        AgeDay , 
        AgeWeek , 
        Notes2 , 
        SourceId , 
        LocationId , 
        DeathLocationId,
        MaleCName, 
        MaleSName, 
        MaleLocation, 
        MaleInfo, 
        FemaleCName, 
        FemaleSName, 
        FemaleLocation, 
        FemaleInfo, 
        Date, 
        MarriageLocation, 
        YearIntVal, 
        MarriageCounty,      
        Witness1CName,
        Witness1SName,
        Witness1Desc,
        Witness2CName,
        Witness2SName,
        Witness2Desc,
        Witness3CName, 
        Witness3SName,
        Witness3Desc,
        Witness4CName, 
        Witness4SName,
        Witness4Desc,
        Witness5CName,
        Witness5SName,
        Witness5Desc,
        Witness6CName,
        Witness6SName,
        Witness6Desc,
        OrigMaleSurname, 
        OrigFemaleSurname,
        MaleOccupation,
        FemaleOccupation,
        FemaleIsKnownWidow,
        MaleIsKnownWidower,
        IsBanns,
        IsLic,      
        MaleAge,
        FemaleAge,
        FemaleFatherCName,
        MaleFatherCName,
        FemaleFatherSName,
        MaleFatherSName,
        FemaleFatherOccupation,
        MaleFatherOccupation,
        SourceDesc, 
        SourceOrigLocat,
        IsCopyHeld,
        IsViewed,
        IsThackrayFound,
        SourceDate,
        SourceDateTo,
        SourceRef,
        SourceParish,
        SourceType,
        PersonId

    }
}